# Generated by Django 5.2.7 on 2026-01-05 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('waiting', '待機中'), ('playing', 'ゲーム中'), ('discussion', '議論中'), ('voting', '投票中'), ('finished', '終了')], default='waiting', max_length=20)),
                ('player_count', models.IntegerField()),
                ('wolf_count', models.IntegerField()),
                ('theme_category', models.IntegerField()),
                ('discussion_minutes', models.IntegerField()),
                ('discussion_seconds', models.IntegerField()),
                ('current_theme', models.CharField(default='', max_length=100)),
                ('wolf_theme', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'スポーツ'), (2, '生活'), (3, '恋愛'), (4, '観光地'), (5, '食べ物・飲み物'), (6, 'ランダム')])),
                ('normal_theme', models.CharField(max_length=100)),
                ('wolf_theme', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_number', models.IntegerField()),
                ('display_name', models.CharField(default='', max_length=50)),
                ('is_wolf', models.BooleanField(default=False)),
                ('theme', models.CharField(default='', max_length=100)),
                ('vote_for', models.IntegerField(blank=True, null=True)),
                ('voted_count', models.IntegerField(default=0)),
                ('is_eliminated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='word_wolf.gamesession')),
            ],
            options={
                'ordering': ['player_number'],
            },
        ),
    ]
