# Generated by Django 5.2.6 on 2026-01-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonmoku_narabe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('finished', 'Finished')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_player',
            field=models.CharField(default='black', max_length=10),
        ),
    ]
