# Generated by Django 5.2.6 on 2026-01-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonmoku_narabe', '0002_game_status_alter_game_current_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.JSONField(default=dict),
        ),
    ]
